---
- name: Install keepassxc package
  pacman: 
    name:
      - keepassxc 
  state: present

- name: adding modules to mkinitcpio

- name: copy nvidia pacman hook file
  file: src=nvidia.hook
        dest=/etc/pacman.d/hooks/nvidia.hook
  state: present

- name: set nvidia-drm.modeset=1 to kernel options