---
- name: Install i3
  pacman:
    name:
      - i3-gaps
      - i3blocks
      - i3lock
      #- i3status
    state: present

- name: install i3blocks modules
  git: repo=https://github.com/vivien/i3blocks-contrib.git dest=~/.config/i3blocks/blocks/ accept_hostkey=yes update=no
  become: yes
  become_user: "{{ user.name }}"

- name: Install py3status
  pacman: name=py3status state=present

- name: Verify that default applications file exists
  file: path=/etc/xdg/mimeapps.list state=touch

- name: Verify header in default applications file
  lineinfile: dest=/etc/xdg/mimeapps.list
              state=present
              line='[Default Applications]'
              insertbefore=BOF

- include: rofi.yml
